on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Python deps
        uses: actions/actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run norminette
        run: |
          python -m pip install --upgrade pip
          python -m pip install norminette
          norminette include/ src/

      - name: Run tests
        run: |
          make test
          cat .log | grep "HOW" && exit 1
